scalar Date

type User {
  _id: ID,
  name: String,
  username: String
}

type Post {
  _id: ID,
  content: String,
  author: User,
  createdAt: Date
}

input PostInput {
  content: String!,
  author: ID!
}

type Query {
  getPostByUser(userId: ID): [Post]
}

type Mutation {
  createPost(input: PostInput): Post
}